version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Your Django Dockerfile path
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  frontend:
    build:
      context: ./frontend  # Adjust this to your React app's directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # React app runs on port 3000
